### PR TITLE
run lotus fetch-params explicitly

### PR DESCRIPTION
**Pull request by mvdan**
(see commit message)

### CODE REVIEW

**Comment by willscott** [comment]
I'm worried that once we do this we are going to have to have a pretty constant stream of updates that we don't have automation on in order to keep the lotus we're testing against up to date. There's a pretty rapid release schedule, and in order to test deal successes, we want the bot to always be against the latest version. I wonder if we have a way to know which version has been promoted to infra and automatically have our tests also run against that?

**Comment by mvdan** [comment]
You're right, though always using the latest master has the same problem and also makes CI/testing more unreliable.

How often does infra get its Lotus version updated, and how? In that process, we could possibly introduce a `sed` find-and-replace command to update the version picked for testing, too. cc @coryschwartz

**Review by gammazero — APPROVED** [review]
LGTM

**Comment by mvdan** [comment]
@willscott what do you want to do here, then? We can agree that pinning Lotus in separate ways for testing and deploying is not great, but not pinning Lotus at all for testing seems worse however you look at it :) Especially since we're currently following master, which could break in unexpected ways at any moment.

I'm happy to look at ways to make the testing and deploying pinning to always be in sync, but I'll need some collaboration with infra on that.

**Comment by willscott** [comment]
I'd rather see tests break and realize it's lotus as a heads up, rather than having that happen first in an infra deployment?
Lotus has a fairly high bar before they merge to master, so i don't think we run into lotus breaking, and if things have been accepted/merged that break this, that's probably a thing we want to know through tests at that point and be able to make noise about it.

**Comment by mvdan** [comment]
@willscott I've undone the bits about pinning lotus, as I think the other changes are still worth merging :)

**Review by willscott — APPROVED** [review]

**Pull request merged**
